### ISSUE TITLE
suggestion: use the README.md as the long description?

### ISSUE THREAD

**Issue by TheTechRobo** [EVasseure/cprint#6]
Try this in the setup.py:

```
with open("README.md","r") as file:
    desc = file.read()
```
 and then use `long_description=contents` and `long_description_content_type='text/markdown'` as parameters to `setup()` .

**Comment by evasseure** [comment]
Updated in https://github.com/evasseure/cprint/commit/1eec7f01fb6add0479290ccd7160f62f96cc8b3e.

Thank you for contributing !
